### ISSUE TITLE
List support for @app.QueryParam

### ISSUE THREAD

**Issue by nistvan86** [redstone-dart/redstone#53]
I've just tried this, and it doesn't work:

```
@app.Route("/id-test")
test(@app.QueryParam("id") List<String> ids) {
 return ids.join("+");
}
```

I'm calling it like:
```
/id-test?id=bla&id=32&id=124
```

Please support this argument variant.

**Comment by luizmineo** [comment]
Sorry for taking so long to reply. I've implemented this feature on v0.6 (which I hope to publish on github soon). Although, this feature requires a breaking change, since the request object must provide the query parameters as a `Map<String, List<String>>`, instead of `Map<String, String>`, so I won't implement it in the current (v0.5) stable branch.

**Comment by nistvan86** [comment]
Thank you! :) Waiting for v0.6 then.

**Comment by luizmineo** [comment]
The first alpha release of Redstone v0.6 is available for test: https://github.com/luizmineo/redstone.dart/tree/v0.6

**Comment by Pacane** [comment]
This doesn't seem to work properly.
