### ISSUE TITLE
cookies or headers bug

### ISSUE THREAD

**Issue by cgarciae** [redstone-dart/redstone#93]
I've been trying to do a basic test with cookies with no luck. Here is my code

```dart
@app.Route ('/cookies')
cookie ()
{
    var cookie = app.request.headers['cookie'];
    app.response = app.response.change(headers: {'set-cookie':'ID=2; Path=/; HttpOnly'});
    return cookie;
}
```
The browser doesn't receive the Set-Cookie header. However, it works if you return a `shelf.Response` with its headers set
```dart
@app.Route ('/cookies')
cookie ()
{
    var cookie = app.request.headers['cookie'];
    return new shelf.Response.ok (cookie, headers: {'set-cookie':'ID=2; Path=/; HttpOnly'});
}
```

**Comment by cgarciae** [comment]
@luizmineo 
Tried digging in the source code to fix the problem. My hypothesis is that the `shelf.Response` modified in the route is not being used because if the response of a route is NOT a `shelf.Response` a new `shelf.Response` is created using the output value from the route's function, but doesn't carry the headers set during the routes execution.
Redstone is a little hard to understand since I don't know `shelf`. Couldn't find the actual line where the route's function is executed. I'll need a basic intro to start contributing with actual code.

**Comment by luizmineo** [comment]
This is the expected behavior. Shelf messages (request and response) are immutable, and the `change()` method always creates a new instance. 

[v0.6](https://github.com/luizmineo/redstone.dart/tree/v0.6) has a better library layout, which are easier to understand. I suggest that you explore this version instead of the current code base.
